### ISSUE TITLE
two timers

### ISSUE THREAD

**Issue by pdgilbert** [rtic-rs/dwt-systick-monotonic#8]
Following example https://github.com/stm32-rs/stm32f4xx-hal/blob/master/examples/adc_dma_rtic.rs I am  trying understand how to add a second timer. I want this in order to use a crate that needs a delay for reading a device. I thought I could do something like
```
        let mono  =    Systick::new(cx.core.SYST,  MONOCLOCK);
        let mono2 = DwtSystick::new(&mut dcb, dwt, cx.core.SYST, MONOCLOCK); 
```
I am new to this and it is very possible that I am completely misunderstand the meaning of  "An implementation of the `Monotonic` trait for `DWT` & `SysTick`" .  The above does not compile because both `Systick` and `DwtSystick` want mutable `cx.core.SYST`. Am I completely off course? Pointers to what I should be trying would be greatly appreciated. Should I be trying to use `EXTI0`  or `TIM3`?

**Comment by AfoHT** [comment]
Both `Systick` and `DwtSystick` assumes complete ownership of `SYST` since they are both meant to interface and set it up.

In short they are mutually exclusive monotonics. Instead you could opt to use some other timer of the f4, maybe https://github.com/kalkyl/f411-rtic/blob/a696fce7d6d19fda2356c37642c4d53547982cca/src/mono.rs

**Comment by pdgilbert** [comment]
Thanks @AfoHT and thanks for the link. I certainly was misunderstanding things. It seems that `stm32f4xx_hal` now allows 
```
use stm32f4xx_hal::{
        fugit::Delay,
        pac::{Peripherals, TIM2},
        prelude::*,
    };
let delay = dp.TIM2.delay_us(&clocks);
```
so using another timer for `delay` is pretty straight forward. Details in the link will be helpful if I attempt other HAL crates.

I have now been trying without success to understand when `DwtSystick` would be used in place of `Systick`. A line or two in the `README.md` would be really helpful for noobies like me.

**Comment by AfoHT** [comment]
Good point about documentation, it is not trivial and based on recent feedback it seems Monotonics needs some more doc effort.

Looking at the README of [systick-monotonic](https://github.com/rtic-rs/systick-monotonic) it highlights that:

> RTIC monotonic implementation using SysTick. Used for testing the RTIC framework in QEMU. Can be used in real apps as well, but it has more overhead than a proper Monotonic implementation.

While [dwt-systick-monotonic](https://github.com/rtic-rs/dwt-systick-monotonic) is more of a *proper* monotonic implementation:
>RTIC monotonic implementation using SysTick and DWT

with the caveat that the user needs to provide access to DWT, something which varies between different hardware.


But I agree it is not obvious :)

**Comment by perlindgren** [comment]
IMHO, `proper` here relates to the timebase and not so much the overhead. Systick alone only does not provide a `proper` time base, it will inevitably drift (as there is no free running timer specifying the actual point in time). DwtSystick on the other hand is `proper` in that respect.

On another note:
Our definition of Monotonic is only partially monotonic as an overflow will eventually happen. The underlying implementation may extend the hardware timer, e.g., from 16/32 to 32/64.. or whatever number of bits allowing larger ranges/time spans to be treated under monotonic semantics. Maybe the Monotonic name is a bit misleading and ModuloTime or something like that should have been used instead, not a biggie but at least the implication should be clear both to the end-user and the implementer of Monotonic timers.

/Per

**Comment by pdgilbert** [comment]
I'm struggling at an even more basic level. Does `DwtSystick` have anything to do with data watch and trace or with code timing, or is it just about the ability to also use DWT as a timer?

**Comment by perlindgren** [comment]
`dwt-systic-monotonic` is strictly an implementation of the Monotonic trait, nothing more, nothing less. It is Ok for demo/experimentation, but I would personally NOT use it for a real project, in that case it is typically preferred to use a HAL implementation of Monotonic if already available. Once you get the hang of embedded Rust ecosystem, the trait is quite easy to implement.
/Per

**Comment by pdgilbert** [comment]
For anyone that may come across this in the future, it seems `fugit::Delay` as indicated above had a temporary status in the git version of `stm32f4xx_hal` I'll try to remember to post here when things stabilize.

**Comment by pdgilbert** [comment]
Thanks @perlindgren, I hope I'll get the hang of it soon.
